-- Estructura de la base de datos para Carta.Digital-MG (Supabase)

-- 1. Crear la tabla de promociones
CREATE TABLE IF NOT EXISTS public.promotions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT DEFAULT ''::text,
    imageurl TEXT NOT NULL,
    imagestoragepath TEXT DEFAULT ''::text,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    active BOOLEAN DEFAULT true,
    createdat TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updatedat TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Habilitar la seguridad a nivel de fila (Row Level Security - RLS)
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;

-- 3. Crear políticas de acceso público para promociones
CREATE POLICY "Permitir lectura pública de promociones" 
ON public.promotions 
FOR SELECT 
USING (true);

CREATE POLICY "Permitir inserción pública de promociones" 
ON public.promotions 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir actualización pública de promociones" 
ON public.promotions 
FOR UPDATE 
USING (true)
WITH CHECK (true);

CREATE POLICY "Permitir borrado público de promociones" 
ON public.promotions 
FOR DELETE 
USING (true);

-- 4. Crear el bucket de storage 'promotions' si no existe
INSERT INTO storage.buckets (id, name, public) 
VALUES ('promotions', 'promotions', true)
ON CONFLICT (id) DO NOTHING;

-- 5. Crear políticas de acceso para el bucket 'promotions'
-- Permitir lectura pública de imágenes
CREATE POLICY "Permitir lectura pública de imágenes"
ON storage.objects 
FOR SELECT 
USING (bucket_id = 'promotions');

-- Permitir inserción pública de imágenes
CREATE POLICY "Permitir inserción pública de imágenes"
ON storage.objects 
FOR INSERT 
WITH CHECK (bucket_id = 'promotions');

-- Permitir borrado público de imágenes
CREATE POLICY "Permitir borrado público de imágenes"
ON storage.objects 
FOR DELETE 
USING (bucket_id = 'promotions');


-- Datos exportados de la base de datos anterior de promociones
BEGIN;
INSERT INTO public.promotions (id, title, description, imageurl, imagestoragepath, date, active, createdat, updatedat) VALUES (8, 'Promoción 6', 'Imagen de promoción 6', 'https://qywviysetikpxwxgkzyj.supabase.co/storage/v1/object/public/promotions/1784220218591_pz289g1urlh.jpg', '1784220218591_pz289g1urlh.jpg', '2026-07-01', TRUE, '2026-07-06 19:12:10.893890+00:00', '2026-07-06 19:12:10.893890+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.promotions (id, title, description, imageurl, imagestoragepath, date, active, createdat, updatedat) VALUES (7, 'Promoción 5', 'Imagen de promoción 5', 'https://qywviysetikpxwxgkzyj.supabase.co/storage/v1/object/public/promotions/1783365130717_default_5.jpg', '1783365130717_default_5.jpg', '2026-07-02', TRUE, '2026-07-06 19:12:09.954983+00:00', '2026-07-06 19:12:09.954983+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.promotions (id, title, description, imageurl, imagestoragepath, date, active, createdat, updatedat) VALUES (6, 'Promoción 4', 'Imagen de promoción 4', 'https://qywviysetikpxwxgkzyj.supabase.co/storage/v1/object/public/promotions/1783366653365_uiwt85n6hp.jpeg', '1783366653365_uiwt85n6hp.jpeg', '2026-07-03', TRUE, '2026-07-06 19:12:09.034412+00:00', '2026-07-06 19:12:09.034412+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.promotions (id, title, description, imageurl, imagestoragepath, date, active, createdat, updatedat) VALUES (5, 'Promoción 3', 'Imagen de promoción 3', 'https://qywviysetikpxwxgkzyj.supabase.co/storage/v1/object/public/promotions/1784220203294_7py4ge8wean.jpg', '1784220203294_7py4ge8wean.jpg', '2026-07-04', TRUE, '2026-07-06 19:12:07.812901+00:00', '2026-07-06 19:12:07.812901+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.promotions (id, title, description, imageurl, imagestoragepath, date, active, createdat, updatedat) VALUES (4, 'Promoción 2', 'Imagen de promoción 2', 'https://qywviysetikpxwxgkzyj.supabase.co/storage/v1/object/public/promotions/1783365125950_default_2.jpg', '1783365125950_default_2.jpg', '2026-07-05', TRUE, '2026-07-06 19:12:06.199515+00:00', '2026-07-06 19:12:06.199515+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.promotions (id, title, description, imageurl, imagestoragepath, date, active, createdat, updatedat) VALUES (3, 'Promoción 1', 'Imagen de promoción 1', 'https://qywviysetikpxwxgkzyj.supabase.co/storage/v1/object/public/promotions/1783365124604_default_1.jpg', '1783365124604_default_1.jpg', '2026-07-06', TRUE, '2026-07-06 19:12:04.266276+00:00', '2026-07-06 19:12:04.266276+00:00') ON CONFLICT (id) DO NOTHING;
COMMIT;
